services:
  postgres:
    image: postgres:latest
    container_name: mpp_container_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backpack
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: node:18
    build:
      context: .
    container_name: mpp-webb-main
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/backpack
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      SESSION_SECRET: your-super-secret-session-key-change-this-in-production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/src
      - /src/node_modules
volumes:
  postgres_data: